/**
 * ETL: generate seed SQL from src/lib/data.ts into supabase/seed.sql.
 *
 *   npx tsx scripts/etl.ts
 *
 * data.ts is the freshest source of truth (enriched from AI_HW_restructured.xlsx).
 * It has no runtime imports, so it is safe to import directly here.
 *
 * Apply the output with either:
 *   - the Supabase MCP (execute_sql), or
 *   - the SQL editor / `supabase db` against supabase/seed.sql
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { PRODUCTS, SUPPLIERS, type Product, type Supplier } from '../src/lib/data'

// ── SQL literal helpers ───────────────────────────────────────────────────────
const txt = (v: string | null | undefined) =>
  v == null ? 'null' : `'${v.replace(/'/g, "''")}'`

// Dollar-quoted JSONB to avoid escaping nested quotes. Guards the (vanishingly
// unlikely) case of the tag appearing inside the payload.
function jsonb(value: unknown): string {
  const json = JSON.stringify(value ?? null)
  let tag = 'j'
  while (json.includes(`$${tag}$`)) tag += 'x'
  return `$${tag}$${json}$${tag}$::jsonb`
}

const textArray = (xs: string[]) =>
  `array[${xs.map(x => `'${x.replace(/'/g, "''")}'`).join(',')}]::text[]`

// ── rows ──────────────────────────────────────────────────────────────────────
function productValues(p: Product): string {
  return `(${[
    txt(p.id), txt(p.name), txt(p.vendor), txt(p.domain), txt(p.sub),
    txt(p.subcat), txt(p.family), txt(p.status), txt(p.node), txt(p.avail),
    txt(p.verified), jsonb(p.attrs ?? {}), jsonb(p.specs ?? []),
    p.bom == null ? 'null' : jsonb(p.bom), jsonb(p.supply ?? {}),
    jsonb(p.rels ?? []), textArray(p.sources ?? []),
  ].join(', ')})`
}

function supplierValues(s: Supplier): string {
  return `(${[
    txt(s.id), txt(s.name), txt(s.hq), textArray(s.models ?? []),
    textArray(s.stages ?? []),
  ].join(', ')})`
}

const lines: string[] = []
lines.push('-- Generated by scripts/etl.ts — do not edit by hand.')
lines.push('begin;')

// Clear derived/edge + core rows (FK-safe order), then reseed.
lines.push('delete from public.product_relationships;')
lines.push('delete from public.product_suppliers;')
lines.push('delete from public.products;')
lines.push('delete from public.suppliers;')

// Suppliers first (products + edges FK to them).
lines.push(
  'insert into public.suppliers (id, name, hq, models, stages) values\n' +
    Object.values(SUPPLIERS).map(supplierValues).join(',\n') + ';'
)

// Products. Column names are the DB's (which differ from the app field names
// in a few places); productValues() emits values in this exact order.
lines.push(
  'insert into public.products\n' +
    '  (id, name, vendor, domain, sub, subcategory, family, status, process_node, available,\n' +
    '   last_verified, attrs, specs, bom, supply_chain, rels, source_ids) values\n' +
    PRODUCTS.map(productValues).join(',\n') + ';'
)

// Derived edges, computed server-side from the JSONB we just inserted (no need
// to ship thousands of literal rows). product_suppliers ← products.supply;
// rows are filtered to existing suppliers to respect the FK.
lines.push(
  `insert into public.product_suppliers (product_id, supplier_id, stage)
select p.id, sup.value, stage.key
from public.products p
cross join lateral jsonb_each(p.supply_chain) as stage(key, arr)
cross join lateral jsonb_array_elements_text(stage.arr) as sup(value)
where exists (select 1 from public.suppliers s where s.id = sup.value);`
)

// product_relationships ← products.rels[]; targets must be existing products.
lines.push(
  `insert into public.product_relationships (from_product_id, to_product_id, type, qty)
select p.id, r.value->>'target', r.value->>'type', (r.value->>'qty')::int
from public.products p
cross join lateral jsonb_array_elements(p.rels) as r(value)
where exists (select 1 from public.products p2 where p2.id = r.value->>'target');`
)

lines.push('commit;')

const out = join(process.cwd(), 'supabase', 'seed.sql')
writeFileSync(out, lines.join('\n\n') + '\n')

console.log(`Wrote ${out}`)
console.log(`  suppliers: ${Object.keys(SUPPLIERS).length}`)
console.log(`  products:  ${PRODUCTS.length}`)
console.log(`  edges (product_suppliers, product_relationships) derived server-side from JSONB`)
